#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Flaportum\Commands\Export as ExportCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new ExportCommand());

$app->run();
